export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

EDITOR=vim
DISABLE_AUTO_TITLE="true"
DISABLE_AUTO_UPDATE="true"
plugins=(history-substring-search git python tmux emacs)

export TERM=xterm-256color
export CONDA_DEFAULT_ENV=${CONDA_DEFAULT_ENV:-base}
export WORKSPACE=${WORKSPACE:-$HOME/workspace}

unsetopt beep

source $ZSH/oh-my-zsh.sh
source $HOME/miniconda3/etc/profile.d/conda.sh
source "$HOME/.cargo/env"


conda activate $CONDA_DEFAULT_ENV

tsws() {
	local repo="${1-__missing__}"
	local fullpath="$WORKSPACE/$repo"

	if [ -d "$fullpath" ]; then
                if [ -f "$fullpath/.zshenv" ]; then
			ZDOTDIR=$fullpath zsh -c "ts -s ${repo} -c ${fullpath}"
                else
			zsh -c "source ${HOME}/.zshrc && ts -s ${repo} -c ${fullpath}"
                fi
	else
		echo  "Not found $WORKSPACE/$repo."
	fi
}

autoload -Uz compinit && compinit
